# Automatic defferentiation

## import libraries


In [1]:
import torch

## variables


In [2]:
x = torch.tensor([2.], requires_grad=True)
y = torch.tensor([-4.], requires_grad=True)

## function

In [3]:
#f = (x + y)**2 + 2*x*y
a = (x + y)**2
b = 2*x*y
f = a + b

f.backward()

In [4]:
print(f)
print(x.data, x.grad)
print(y.data, y.grad)

tensor([-12.], grad_fn=<AddBackward0>)
tensor([2.]) tensor([-12.])
tensor([-4.]) tensor([0.])
